/**
 * @bapm/core — domain library for Better Agent Package Manager.
 *
 * Thin package entry: public surface is assembled in app/publicApi.
 * FEOD layout: app / modules / common / globals / pages (stub).
 */

export {
  type BapmManifest,
  type BapmDependency,
  type DependencyEntry,
  type DependencyLists,
  type DiscoverManifestOptions,
  type DiscoveredManifest,
  type LoadManifestOptions,
  type LoadManifestResult,
  type ManifestFilename,
  type ObjectDependency,
  type RegistryEntry,
  type ManifestErrorCode,
  type ManifestWarning,
  ManifestError,
  APM_MANIFEST_FILE,
  BAPM_MANIFEST_FILE,
  discoverManifestPath,
  loadManifest,
  parseManifest,
  parseManifestDocument,
  loadYamlDocument,
  type DiscoverLockfileOptions,
  type DiscoveredLockfile,
  type LoadLockfileOptions,
  type LoadLockfileResult,
  type LockedDependency,
  type LockfileDocument,
  type LockfileInput,
  type LockFilename,
  type WriteLockfileOptions,
  type LockfileErrorCode,
  LockfileError,
  APM_LOCK_FILE,
  BAPM_LOCK_FILE,
  discoverLockfilePath,
  loadLockfile,
  loadLockfileOrNull,
  writeLockfile,
  parseLockfile,
  parseLockfileDocument,
  serializeLockfile,
  isSemanticallyEquivalent,
  BAPM_NAME,
  getVersion,
} from "./app/publicApi.ts";
