import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  discoverPrimitives,
  resolvePrimitiveConflicts,
  type AttributedPrimitive,
} from "@/modules/Primitives";
import { APM_MODULES_DIR } from "@/modules/Resolver";
import type {
  CompileAgentsMdOptions,
  CompileAgentsMdResult,
  CompileAttributionEntry,
} from "./types.ts";

/**
 * Discover primitives and emit deterministic `AGENTS.md` (cursor host only).
 * Does not emit CLAUDE.md / GEMINI.md / copilot-instructions.
 */
export function compileAgentsMd(options: CompileAgentsMdOptions = {}): CompileAgentsMdResult {
  const cwd = resolve(options.cwd ?? process.cwd());
  const validate = options.validate === true;
  const dryRun = options.dryRun === true;
  const outputFile = options.outputFile ?? "AGENTS.md";
  const modulesDir = options.modulesDir ?? join(cwd, APM_MODULES_DIR);

  const raw = discoverPrimitives({ cwd, modulesDir });
  const { primitives } = resolvePrimitiveConflicts({ primitives: raw });
  const sorted = sortPrimitives(primitives);
  const content = renderAgentsMd(sorted, cwd);
  const attribution = toAttribution(sorted);

  const outPath = join(cwd, outputFile);
  let wrote = false;
  // validate wins over dryRun: never write when either is set
  if (!validate && !dryRun) {
    const parent = dirname(outPath);
    if (!existsSync(parent)) mkdirSync(parent, { recursive: true });
    writeFileSync(outPath, content, "utf8");
    wrote = true;
  }

  return {
    ok: true,
    path: outPath,
    content,
    wrote,
    primitivesCount: sorted.length,
    attribution,
  };
}

export const compileProject = compileAgentsMd;
export const runCompile = compileAgentsMd;
export const emitAgentsMd = compileAgentsMd;

function toAttribution(primitives: AttributedPrimitive[]): CompileAttributionEntry[] {
  return primitives.map((p) => {
    const entry: CompileAttributionEntry = {
      name: String(p.name ?? "unnamed"),
      type: String(p.type ?? "primitive"),
    };
    const path = typeof p.path === "string" ? p.path.trim() : "";
    if (path) entry.path = path;
    return entry;
  });
}

function sortPrimitives(primitives: AttributedPrimitive[]): AttributedPrimitive[] {
  return [...primitives].sort((a, b) => {
    const ta = String(a.type ?? "");
    const tb = String(b.type ?? "");
    if (ta !== tb) return ta.localeCompare(tb);
    const na = String(a.name ?? "");
    const nb = String(b.name ?? "");
    if (na !== nb) return na.localeCompare(nb);
    return String(a.path ?? "").localeCompare(String(b.path ?? ""));
  });
}

function renderAgentsMd(primitives: AttributedPrimitive[], cwd: string): string {
  const sections: string[] = [];
  sections.push("# AGENTS.md");
  sections.push("");
  sections.push("<!-- Generated by bapm compile. Do not edit by hand. -->");
  sections.push("");

  if (primitives.length === 0) {
    sections.push("_No discoverable primitives._");
    sections.push("");
    return sections.join("\n");
  }

  for (const p of primitives) {
    const type = String(p.type ?? "primitive");
    const name = String(p.name ?? "unnamed");
    sections.push(`## ${name} (${type})`);
    sections.push("");
    const body = readPrimitiveBody(p, cwd);
    sections.push(body.trimEnd());
    sections.push("");
  }

  return sections.join("\n");
}

function readPrimitiveBody(p: AttributedPrimitive, cwd: string): string {
  if (typeof p.content === "string") return p.content;
  const path = p.path
    ? resolve(p.path.startsWith("/") || /^[A-Za-z]:/.test(p.path) ? p.path : join(cwd, p.path))
    : undefined;
  if (path && existsSync(path)) {
    try {
      return readFileSync(path, "utf8");
    } catch {
      /* fall through */
    }
  }
  return `# ${p.name ?? "unnamed"}\n`;
}
