import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  COPILOT_NATIVE_ENABLE_SUFFIX,
  COPILOT_NATIVE_MARKETPLACE_ID,
  COPILOT_NATIVE_MODULES_PATH,
  COPILOT_NATIVE_SETTINGS_REL,
} from "./constants.ts";
import { readCopilotNativeLedger } from "./catalog.ts";
import { CopilotNativeRegistrationError } from "./errors.ts";
import type { AdmittedCopilotNativePlugin } from "./types.ts";

type SettingsDoc = Record<string, unknown>;

/**
 * Merge owned Copilot settings keys for native registration.
 * Fail closed on invalid plain JSON; refuse conflicting unowned `apm` marketplace path;
 * re-adopt matching path; retire stale `*@apm` enable keys.
 */
export function mergeCopilotNativeSettings(
  cwd: string,
  admitted: AdmittedCopilotNativePlugin[],
): void {
  const abs = join(resolve(cwd), COPILOT_NATIVE_SETTINGS_REL);
  const existing = loadSettingsOrThrow(abs, cwd);
  assertMarketplaceOwnership(cwd, existing);

  const marketplaces = isPlainObject(existing.extraKnownMarketplaces)
    ? { ...(existing.extraKnownMarketplaces as Record<string, unknown>) }
    : {};

  marketplaces[COPILOT_NATIVE_MARKETPLACE_ID] = {
    source: {
      source: "directory",
      path: COPILOT_NATIVE_MODULES_PATH,
    },
  };

  const enabled = isPlainObject(existing.enabledPlugins)
    ? { ...(existing.enabledPlugins as Record<string, unknown>) }
    : {};

  const keepSuffix = COPILOT_NATIVE_ENABLE_SUFFIX;
  for (const key of Object.keys(enabled)) {
    if (key.endsWith(keepSuffix)) delete enabled[key];
  }
  for (const plugin of admitted) {
    enabled[`${plugin.pluginName}${keepSuffix}`] = true;
  }

  const next: SettingsDoc = {
    ...existing,
    extraKnownMarketplaces: marketplaces,
    enabledPlugins: enabled,
  };

  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, `${JSON.stringify(next, null, 2)}\n`, "utf8");
}

/** Fail-closed validation before any catalog/ledger writes. */
export function assertCopilotNativeSettingsWritable(cwd: string): void {
  const abs = join(resolve(cwd), COPILOT_NATIVE_SETTINGS_REL);
  const existing = loadSettingsOrThrow(abs, cwd);
  assertMarketplaceOwnership(cwd, existing);
}

/**
 * Retire owned `@apm` enable keys and optionally drop owned marketplace when empty.
 * Preserves unrelated keys. Fail closed on invalid JSON (same as merge).
 */
export function retireCopilotNativeSettings(
  cwd: string,
  remaining: AdmittedCopilotNativePlugin[],
): void {
  const abs = join(resolve(cwd), COPILOT_NATIVE_SETTINGS_REL);
  if (!existsSync(abs) && remaining.length === 0) return;
  if (!existsSync(abs)) {
    if (remaining.length > 0) mergeCopilotNativeSettings(cwd, remaining);
    return;
  }
  mergeCopilotNativeSettings(cwd, remaining);
}

function loadSettingsOrThrow(abs: string, cwd: string): SettingsDoc {
  if (!existsSync(abs)) return {};
  const raw = readFileSync(abs, "utf8");
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!isPlainObject(parsed)) {
      throw new Error("root must be an object");
    }
    return parsed;
  } catch (cause) {
    throw new CopilotNativeRegistrationError(
      "COPILOT_NATIVE_SETTINGS_INVALID",
      `Invalid Copilot settings JSON at ${COPILOT_NATIVE_SETTINGS_REL}: plain JSON required (JSONC/comments not allowed)`,
      {
        details: { path: abs, cwd },
        cause,
      },
    );
  }
}

function assertMarketplaceOwnership(cwd: string, settings: SettingsDoc): void {
  const marketplaces = settings.extraKnownMarketplaces;
  if (!isPlainObject(marketplaces)) return;
  const apm = marketplaces[COPILOT_NATIVE_MARKETPLACE_ID];
  if (apm === undefined) return;

  const pathVal = extractMarketplacePath(apm);
  const normalized = normalizeModulesPath(pathVal);
  if (normalized === COPILOT_NATIVE_MODULES_PATH) {
    // Matching path — re-adopt (ledger regenerated by caller).
    return;
  }

  const ledger = readCopilotNativeLedger(cwd);
  if (ledger?.ownedMarketplace === true && ledger.marketplaceId === COPILOT_NATIVE_MARKETPLACE_ID) {
    // Owned ledger allows rewrite to modules path.
    return;
  }

  throw new CopilotNativeRegistrationError(
    "COPILOT_NATIVE_MARKETPLACE_COLLISION",
    `Refusing conflicting unowned apm marketplace path "${pathVal ?? "(missing)"}" (expected ${COPILOT_NATIVE_MODULES_PATH}); ownership collision`,
    {
      details: {
        path: pathVal,
        expected: COPILOT_NATIVE_MODULES_PATH,
      },
    },
  );
}

function extractMarketplacePath(entry: unknown): string | undefined {
  if (!isPlainObject(entry)) return undefined;
  const source = (entry.source ?? entry) as Record<string, unknown>;
  if (typeof source.path === "string") return source.path;
  const nested = source.source;
  if (isPlainObject(nested) && typeof nested.path === "string") return nested.path;
  return undefined;
}

function normalizeModulesPath(pathVal: string | undefined): string | undefined {
  if (typeof pathVal !== "string") return undefined;
  const n = pathVal.replace(/\\/g, "/").replace(/\/+$/, "");
  if (n === COPILOT_NATIVE_MODULES_PATH || n.endsWith(`/${COPILOT_NATIVE_MODULES_PATH}`)) {
    return COPILOT_NATIVE_MODULES_PATH;
  }
  return n;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
