import { existsSync, mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "vite-plus/test";
import {
  SHARED_COMMAND_FRONTMATTER_KEYS,
  compileMarkdownReport,
  filterFrontmatterKeys,
  renderPrimitivesMarkdown,
  writeDeployedFile,
} from "../src/index.ts";
import type { AttributedPrimitive } from "../src/index.ts";

function prim(
  partial: Partial<AttributedPrimitive> & Pick<AttributedPrimitive, "name" | "type">,
): AttributedPrimitive {
  return {
    source: "local",
    path: `/tmp/${partial.name}`,
    content: `# body ${partial.name}`,
    ...partial,
  };
}

describe("writeDeployedFile", () => {
  test("writes under deploy roots and returns inventory row", () => {
    const cwd = mkdtempSync(join(tmpdir(), "bapm-write-deployed-"));
    const row = writeDeployedFile({
      cwd,
      deployRoots: [".cursor"],
      destRel: ".cursor/rules/hello.mdc",
      content: "hello\n",
      primitive: { name: "hello", packageName: "pkg" },
    });
    expect(row.path).toBe(".cursor/rules/hello.mdc");
    expect(row.primitive).toEqual({ name: "hello", packageName: "pkg" });
    expect(readFileSync(join(cwd, ".cursor/rules/hello.mdc"), "utf8")).toBe("hello\n");
  });

  test("refuses path outside deploy roots", () => {
    const cwd = mkdtempSync(join(tmpdir(), "bapm-write-refuse-"));
    expect(() =>
      writeDeployedFile({
        cwd,
        deployRoots: [".cursor"],
        destRel: "elsewhere/x.md",
        content: "nope",
      }),
    ).toThrow(/deploy roots/);
    expect(existsSync(join(cwd, "elsewhere/x.md"))).toBe(false);
  });
});

describe("renderPrimitivesMarkdown", () => {
  test("sorts and emits default AGENTS-style sections", () => {
    const md = renderPrimitivesMarkdown({
      title: "# AGENTS.md",
      primitives: [prim({ name: "b", type: "skill" }), prim({ name: "a", type: "agent" })],
    });
    expect(md).toContain("# AGENTS.md");
    expect(md).toContain("<!-- Generated by bapm compile. Do not edit by hand. -->");
    expect(md.indexOf("## a (agent)")).toBeLessThan(md.indexOf("## b (skill)"));
    expect(md).toContain("# body a");
  });

  test("filter + custom empty message", () => {
    const md = renderPrimitivesMarkdown({
      title: "# AGENTS.md",
      primitives: [prim({ name: "i", type: "instruction" })],
      filter: (p) => !/instruction/i.test(String(p.type)),
      emptyMessage: "_No discoverable instruction primitives._",
    });
    expect(md).toContain("_No discoverable instruction primitives._");
    expect(md).not.toContain("## i");
  });

  test("custom sectionHeading", () => {
    const md = renderPrimitivesMarkdown({
      title: "# GEMINI.md",
      primitives: [prim({ name: "only", type: "instruction" })],
      sectionHeading: (p) => String(p.name),
    });
    expect(md).toContain("## only\n");
    expect(md).not.toContain("(instruction)");
  });
});

describe("compileMarkdownReport", () => {
  test("preview does not write", () => {
    const cwd = mkdtempSync(join(tmpdir(), "bapm-compile-preview-"));
    const report = compileMarkdownReport({
      cwd,
      outputFile: "AGENTS.md",
      write: false,
      content: "# hi\n",
    });
    expect(report).toEqual({ path: "AGENTS.md", content: "# hi\n", wrote: false });
    expect(existsSync(join(cwd, "AGENTS.md"))).toBe(false);
  });

  test("write + requireBasename", () => {
    const cwd = mkdtempSync(join(tmpdir(), "bapm-compile-write-"));
    const report = compileMarkdownReport({
      cwd,
      outputFile: "GEMINI.md",
      write: true,
      content: "# g\n",
      requireBasename: "GEMINI.md",
    });
    expect(report.wrote).toBe(true);
    expect(readFileSync(join(cwd, "GEMINI.md"), "utf8")).toBe("# g\n");
  });

  test("rejects escape and wrong basename", () => {
    const cwd = mkdtempSync(join(tmpdir(), "bapm-compile-escape-"));
    expect(() =>
      compileMarkdownReport({
        cwd,
        outputFile: "../out.md",
        write: false,
        content: "x",
      }),
    ).toThrow(/cwd-relative/);
    expect(() =>
      compileMarkdownReport({
        cwd,
        outputFile: "OTHER.md",
        write: false,
        content: "x",
        requireBasename: "GEMINI.md",
      }),
    ).toThrow(/basename must be GEMINI.md/);
  });
});

describe("filterFrontmatterKeys", () => {
  test("drops non-preserved keys in encounter order", () => {
    const source = `---
description: hi
extra: 1
model: fast
gone: x
---
body
`;
    const { content, droppedKeys } = filterFrontmatterKeys(source, SHARED_COMMAND_FRONTMATTER_KEYS);
    expect(droppedKeys).toEqual(["extra", "gone"]);
    expect(content).toContain("description: hi");
    expect(content).toContain("model: fast");
    expect(content).not.toContain("extra:");
    expect(content).toContain("body");
  });

  test("no fence returns source unchanged", () => {
    const source = "just text\n";
    expect(filterFrontmatterKeys(source, SHARED_COMMAND_FRONTMATTER_KEYS)).toEqual({
      content: source,
      droppedKeys: [],
    });
  });
});
