/**
 * Thin compile → AGENTS.md omitting instruction/steering primitives.
 */
import { afterEach, describe, expect, test } from "vite-plus/test";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
  createTempProject,
  ensureKiroDir,
  loadKiroIntegration,
  writePrimitiveFile,
} from "./helpers.ts";

describe("kiro compile", () => {
  let cleanup: (() => void) | undefined;

  afterEach(() => {
    cleanup?.();
    cleanup = undefined;
  });

  test("compile writes AGENTS.md and omits instruction bodies", async () => {
    const project = createTempProject("bapm-kiro-compile-");
    cleanup = project.cleanup;
    ensureKiroDir(project.cwd);

    const instruction = writePrimitiveFile(
      project.cwd,
      "style.md",
      "# Steering-only body that must not appear in AGENTS.md\n",
    );
    const skillDir = join(project.cwd, "skill");
    const skillPath = writePrimitiveFile(
      skillDir,
      "SKILL.md",
      "---\nname: demo\n---\n# Demo skill body\n",
    );

    const target = loadKiroIntegration();
    const report = await target.compile!(
      [
        { name: "style", type: "instruction", source: "local", path: instruction },
        { name: "demo", type: "skill", source: "local", path: skillPath },
      ],
      { cwd: project.cwd, write: true },
    );

    expect(report.path).toMatch(/AGENTS\.md$/);
    expect(existsSync(join(project.cwd, "AGENTS.md"))).toBe(true);
    const body = readFileSync(join(project.cwd, "AGENTS.md"), "utf8");
    expect(body).toMatch(/Generated by bapm compile/i);
    expect(body).toMatch(/Demo skill body/);
    expect(body).not.toMatch(/Steering-only body that must not appear/);
  });
});
