/**
 * Package public API assembly for @bapm/core.
 * Re-exports Manifest + Lockfile + Resolver + Install + lifecycle module surfaces.
 */

export type {
  BapmManifest,
  BapmDependency,
  DependencyEntry,
  DependencyLists,
  DiscoverManifestOptions,
  DiscoveredManifest,
  LoadManifestOptions,
  LoadManifestResult,
  ManifestFilename,
  ObjectDependency,
  RegistryEntry,
  TargetIntegrationMap,
  ManifestErrorCode,
  ManifestWarning,
  WriteManifestOptions,
  WriteProducerManifestOptions,
  WriteProducerManifestResult,
  CreateMinimalManifestOptions,
  CreatePluginJsonOptions,
  PluginJsonAuthor,
  PluginJsonDocument,
  WritePluginJsonOptions,
} from "@/modules/Manifest";

export {
  ManifestError,
  APM_MANIFEST_FILE,
  BAPM_MANIFEST_FILE,
  discoverManifestPath,
  loadManifest,
  parseManifest,
  parseManifestDocument,
  loadYamlDocument,
  serializeManifest,
  writeManifest,
  writeProducerManifest,
  emitManifest,
  writeManifestValidated,
  createMinimalManifest,
  createMinimalManifestDocument,
  validatePluginName,
  validateProjectName,
  isValidPluginName,
  isValidProjectName,
  createPluginJson,
  createPluginJsonDocument,
  buildPluginJson,
  serializePluginJson,
  writePluginJson,
  writePluginJsonFile,
  emitPluginJson,
  CANONICAL_TARGET_TOKENS,
  TARGET_ALIAS_TOKENS,
  VENDOR_TARGET_RE,
  isValidTargetToken,
  isExemptInsecureHost,
} from "@/modules/Manifest";

export type {
  DiscoverLockfileOptions,
  DiscoveredLockfile,
  LoadLockfileOptions,
  LoadLockfileResult,
  LockedDependency,
  LockfileDocument,
  LockfileInput,
  LockFilename,
  WriteLockfileOptions,
  LockfileErrorCode,
  TreeSha256Violation,
} from "@/modules/Lockfile";

export {
  LockfileError,
  APM_LOCK_FILE,
  BAPM_LOCK_FILE,
  discoverLockfilePath,
  loadLockfile,
  loadLockfileOrNull,
  writeLockfile,
  parseLockfile,
  parseLockfileDocument,
  serializeLockfile,
  isSemanticallyEquivalent,
  computeCanonicalTreeSha256,
  treeSha256Equal,
  formatTreeSha256Violation,
  isGitSourcedLockEntry,
  locateGitPackageTree,
  collectTreeSha256Violations,
} from "@/modules/Lockfile";

export type {
  ClassifiedDependency,
  DependencyKind,
  DownloadArgs,
  DownloadPackageSpec,
  DownloadPackagesOptions,
  Downloader,
  FakeTag,
  GitRemote,
  ResolveAndLockOptions,
  ResolveAndLockResult,
  ResolveDependencyGraphOptions,
  ResolveGraphResult,
  ResolvePorts,
  ResolvedNode,
  TagLister,
  ResolverErrorCode,
  PurgeInstallPathArgs,
} from "@/modules/Resolver";

export {
  ResolverError,
  APM_MODULES_DIR,
  MAX_RESOLVE_DEPTH,
  DEFAULT_PARALLEL_DOWNLOADS,
  classifyDependencyRef,
  resolveDependencyGraph,
  downloadPackages,
  resolveAndLock,
  purgeModulesInstallPaths,
  normalizeRepoIdentity,
  toLockRepoUrl,
  identityToCacheDir,
  pickHighestSatisfyingTag,
  pickHighestInIntersection,
  pickTightestRange,
  createDefaultDownloader,
  createDefaultGitRemote,
  createDefaultTagLister,
  createPeelAwareTagLister,
  materializeRegistryNodes,
  DEFAULT_LOCAL_ROOT,
  effectiveLocalPath,
  localRootGitignorePattern,
  collectLocalSourcePaths,
  ensureLocalRootUntracked,
  ensureLocalSourcesUntracked,
} from "@/modules/Resolver";

export type {
  AttributedPrimitive,
  DiscoverPrimitivesOptions,
  PrimitiveConflictDiagnostic,
  PrimitiveSource,
  PrimitiveType,
  ResolvePrimitiveConflictsOptions,
  ResolvePrimitiveConflictsResult,
  PrimitivesErrorCode,
} from "@/modules/Primitives";

export {
  PrimitivesError,
  discoverPrimitives,
  resolvePrimitiveConflicts,
  resolveConflicts,
} from "@/modules/Primitives";

export type {
  AgentPluginAuthor,
  AgentPluginDiagnostic,
  AgentPluginManifest,
  AgentPluginMcpServer,
  AgentPluginSkill,
  CreateAgentPluginManifestOptions,
  DiscoverAgentPluginMcpOptions,
  DiscoverAgentPluginMcpResult,
  DiscoverAgentPluginSkillsOptions,
  DiscoverAgentPluginSkillsResult,
  LoadedAgentPluginManifest,
  LoadAgentPluginManifestOptions,
  AgentPluginsErrorCode,
  WrittenAgentPluginManifest,
  WriteAgentPluginManifestOptions,
} from "@/modules/AgentPlugins";
export {
  AGENT_PLUGIN_MANIFEST_SCHEMA_V1,
  AgentPluginsError,
  loadAgentPluginManifest,
  validateAgentPluginManifest,
  discoverAgentPluginSkills,
  discoverAgentPluginMcp,
  createAgentPluginManifest,
  serializeAgentPluginManifest,
  writeAgentPluginManifest,
} from "@/modules/AgentPlugins";

export type {
  EnforceFrozenOptions,
  InstallOptions,
  InstallResult,
  RunInstallOptions,
  InstallErrorCode,
  DeployedHashViolation,
  ResolvedDeployedFile,
} from "@/modules/Install";

export {
  InstallError,
  enforceFrozen,
  isCiEnvTruthy,
  resolveEffectiveFrozen,
  runInstall,
  installProject,
  declaredTargetIds,
  declaredTargetIntegrationMap,
  DEPLOYED_HASH_ALGO,
  hashFileBytes,
  hashFileAt,
  safeResolveUnderCwd,
  cleanupOrphanDeployedFiles,
  verifyDeployedFileHashes,
  collectDeployedHashViolations,
  collectDeployedHashes,
  applyDeployedHashesToLock,
} from "@/modules/Install";

export type { ResolveEffectiveFrozenOptions } from "@/modules/Install";

export type {
  RunUpdateOptions,
  UpdatePlanEntry,
  UpdateResult,
  UpdateErrorCode,
} from "@/modules/Update";
export { UpdateError, runUpdate, updateProject } from "@/modules/Update";

export type {
  OutdatedRow,
  OutdatedResult,
  RunOutdatedOptions,
  OutdatedErrorCode,
} from "@/modules/Outdated";
export {
  DEFAULT_PARALLEL_CHECKS,
  OutdatedError,
  runOutdated,
  checkOutdated,
  outdated,
  abbreviateSha,
  findLatestAnnotatedTag,
  isFullRevisionPin,
  packageBasenameFromRepo,
} from "@/modules/Outdated";
export type { AnnotatedTagCandidate } from "@/modules/Outdated";

export type { RunUninstallOptions, UninstallResult, UninstallErrorCode } from "@/modules/Uninstall";
export { UninstallError, runUninstall, uninstallPackages, uninstall } from "@/modules/Uninstall";

export type { RunPruneOptions, PruneResult, PruneErrorCode } from "@/modules/Prune";
export { PruneError, runPrune, pruneModules, prune } from "@/modules/Prune";

export type {
  DepsListResult,
  DepsTreeResult,
  DepsWhyError,
  DepsWhyPackage,
  DepsWhyPath,
  DepsWhyPathNode,
  DepsWhyResult,
  RunDepsOptions,
} from "@/modules/Deps";
export {
  listDeps,
  depsList,
  runDepsList,
  treeDeps,
  depsTree,
  runDepsTree,
  whyDeps,
  depsWhy,
  runDepsWhy,
  resolvePackageQuery,
  repoBasename,
  repoOwnerRepo,
} from "@/modules/Deps";

export type {
  AuditCiCheck,
  AuditCiCheckName,
  AuditCiFormat,
  AuditCiResult,
  AuditCiStructuredReport,
  AuditCiSummary,
  RunAuditCiOptions,
} from "@/modules/Audit";
export {
  runAuditCi,
  auditCi,
  runAudit,
  formatAuditCiJson,
  formatAuditCiSarif,
  summarizeChecks,
  toStructuredReport,
} from "@/modules/Audit";

export type {
  ExportSbomFailure,
  ExportSbomOptions,
  ExportSbomResult,
  ExportSbomSuccess,
  InventoryDep,
  LicenseClass,
  LicenseKind,
  SbomFormat,
} from "@/modules/Export";
export {
  CYCLONEDX_SPEC_VERSION,
  FIXED_EPOCH_TIMESTAMP,
  FORMAT_CYCLONEDX,
  FORMAT_SPDX,
  SPDX_VERSION,
  SUPPORTED_FORMATS,
  buildPurl,
  scrubUrl,
  componentName,
  componentVersion,
  classifyDeclaredLicense,
  KIND_EXPRESSION,
  KIND_ID,
  KIND_NAMED,
  formatUnsupportedMessage,
  normalizeFormat,
  serializeSbom,
  exportSbom,
} from "@/modules/Export";

export type { DoctorResult, RunDoctorOptions, DoctorCheck } from "@/modules/Doctor";
export { runDoctor, doctor, checkDoctor } from "@/modules/Doctor";

export type {
  RunPackOptions,
  RunPackResult,
  ExtractPackArchiveOptions,
  ExtractPackArchiveResult,
  CheckReleaseTagOptions,
  CheckReleaseTagResult,
  PackErrorCode,
} from "@/modules/Pack";

export {
  PackError,
  runPack,
  packProject,
  packArchive,
  extractPackArchive,
  unpackArchive,
  extractPack,
  MAX_SAFE_ENTRIES,
  MAX_SAFE_UNCOMPRESSED_BYTES,
  SafeExtractError,
  assertSafeZipCentralDirectory,
  parseZipCentralDirectory,
  safeExtractZip,
  checkReleaseTag,
  checkRelease,
  runCheckRelease,
  isSecretPackPath,
  describeSecretRefuse,
} from "@/modules/Pack";

export type {
  DiscoverPolicyOptions,
  DiscoveredPolicy,
  EvaluatePolicyOptions,
  EvaluatePolicyResult,
  LoadPolicyOptions,
  LoadPolicyResult,
  ParsePolicyResult,
  PolicyCandidate,
  PolicyDependencies,
  PolicyDependencyInput,
  PolicyDocument,
  PolicyEnforcement,
  PolicyExecutables,
  PolicyGateOptions,
  PolicyGateResult,
  PolicyViolation,
  PolicyErrorCode,
  PolicyWarning,
  PolicyStatusOptions,
  PolicyStatusOutcome,
  PolicyStatusReport,
  PolicyStatusRuleCounts,
} from "@/modules/Policy";

export {
  PolicyError,
  APM_POLICY_FILE,
  BAPM_POLICY_FILE,
  DEFAULT_POLICY_PROVIDERS,
  POLICY_DISCOVERY_PROVIDERS,
  defaultPolicyProviders,
  POLICY_PROVIDER_LOCAL,
  POLICY_PROVIDER_GITHUB_OWNER_DOTGITHUB,
  discoverPolicyPath,
  discoverLocalPolicyPath,
  discoverPolicyWithProviders,
  runPolicyDiscovery,
  discoverPolicyProviders,
  selectProjectRemote,
  selectGitRemoteForPolicy,
  resolveProjectRemote,
  listGitRemotes,
  loadPolicy,
  parsePolicy,
  parsePolicyDocument,
  resolvePolicyChain,
  resolveExtends,
  resolvePolicyExtends,
  mergePolicyChain,
  POLICY_EXTENDS_MAX_DEPTH,
  mergePolicies,
  mergePolicyDocuments,
  mergePolicy,
  hostClassOf,
  policyHostClass,
  hostClassForPolicy,
  resolveHostClass,
  IMPLEMENTATION_DEFAULT_HOST,
  evaluateInstallPolicy,
  evaluatePolicy,
  evaluatePolicyRules,
  isPolicyDisabled,
  runPolicyGate,
  assertPolicyGateAllows,
  runPolicyStatus,
  redactPolicyRef,
} from "@/modules/Policy";

export type {
  ProviderHostClass,
  RegistryAliasEntry,
  RegistryAliasMap,
  ResolvedCredentials,
  ResolveCredentialsOptions,
  SameCredentialHostClassOptions,
  BuildGitChildEnvOptions,
  FetchWithRedirectAuthDropInit,
} from "@/modules/Auth";

export {
  credentialHostClassOf,
  credentialHostClass,
  authHostClassOf,
  hostClassForCredentials,
  credentialHostClassForHost,
  sameCredentialHostClass,
  credentialHostClassesEqual,
  hostsShareCredentialClass,
  buildAliasCredentialClassMap,
  selectProviderClassForHost,
  effectiveProviderClassForHost,
  classifyProviderHostClass,
  resolveCredentialsForHost,
  resolveAuthCredentialsForHost,
  resolveHostCredentials,
  authHeadersForResolved,
  fetchWithRedirectAuthDrop,
  fetchRedirectAuthDrop,
  redirectSafeFetch,
  fetchWithCredentialHostClassRedirects,
  buildGitChildEnv,
  buildHardenedGitEnv,
  createGitChildEnv,
  gitChildEnvForHost,
  mayAttachGitCredential,
  PLATFORM_TOKEN_ENV_NAMES,
  collectAdoHosts,
} from "@/modules/Auth";

export type {
  ExecutableGrantEntry,
  ExecutableGrantSurface,
  ExecutableTrustDecision,
  ExecutableTrustOutcome,
  EvaluateExecutableTrustOptions,
  EvaluateRequiredPackagePresenceOptions,
  EvaluateRequiredPackagePresenceResult,
  GrantSurfaceInput,
  OrgExecutables,
  ParseExecutableGrantsOptions,
  RequiredPackagePresenceDiagnostic,
  RequiredPackageTrustOutcome,
  ResolveExecutableTrustOptions,
  SaveUserExecutableGrantsOptions,
  UserExecutableGrants,
  UserExecutableStoreOptions,
} from "@/modules/ExecutableTrust";

export {
  evaluateExecutableTrust,
  evaluateMcpExecutableTrust,
  gateExecutableMcp,
  checkExecutableTrust,
  hasGrantSurface,
  parseExecutableGrants,
  resolveExecutableTrust,
  classifyExecutableTrust,
  loadUserExecutableGrants,
  loadUserExecutables,
  loadExecutableUserGrants,
  readUserExecutableGrants,
  saveUserExecutableGrants,
  saveUserExecutables,
  saveExecutableUserGrants,
  writeUserExecutableGrants,
  persistUserExecutableGrant,
  resolveUserConfigRoot,
  userConfigJsonPath,
  userGrantsToSurface,
  evaluateRequiredPackagePresence,
  classifyRequiredPackagePresence,
  evaluateRequireLockPresence,
  evaluateRequiredPackagesFromLock,
} from "@/modules/ExecutableTrust";

export type {
  CollectedMcpServer,
  CollectMcpServersOptions,
  CollectMcpServersResult,
  ApplyMcpInventoryOptions,
  BakeMcpStringMapOptions,
  BakeableMcpServer,
} from "@/modules/Mcp";

export {
  collectMcpServers,
  applyMcpInventoryToLock,
  bakeMcpStringMap,
  bakeMcpStringValue,
  bakeMcpServerMaps,
  McpEnvBakeError,
} from "@/modules/Mcp";

export type {
  CompileAgentsMdOptions,
  CompileAgentsMdResult,
  CompileAttributionEntry,
} from "@/modules/Compile";

export { compileAgentsMd, compileProject, runCompile, emitAgentsMd } from "@/modules/Compile";

export type {
  CacheCleanOptions,
  CacheCleanResult,
  CacheInfoOptions,
  CacheInfoResult,
} from "@/modules/Cache";

export {
  cacheInfo,
  getCacheInfo,
  modulesCacheInfo,
  cacheClean,
  cleanModulesCache,
} from "@/modules/Cache";

export type {
  BuildPublishArchiveOptions,
  BuildPublishArchiveResult,
  CheckSelfUpdateOptions,
  CheckSelfUpdateResult,
  CreateRegistryClientOptions,
  RegistryClient,
  RegistryHttpRequest,
  RegistryHttpResponse,
  RegistryHttpTransport,
  RegistryVersionInfo,
  RegistryErrorCode,
} from "@/modules/Registry";

export {
  RegistryError,
  EXPERIMENTAL_REGISTRIES_ENV,
  isExperimentalRegistriesEnabled,
  experimentalRegistriesRemediation,
  assertExperimentalRegistriesEnabled,
  createRegistryClient,
  createRegistryHttpClient,
  createPackageRegistryClient,
  sha256Digest,
  sha256Hex,
  digestsEqual,
  verifyArchiveDigest,
  createFetchTransport,
  resolveRegistryToken,
  buildPublishArchive,
  createPublishArchive,
  packPublishArchive,
  buildRegistryPublishZip,
  checkSelfUpdate,
  compareSelfUpdate,
  runSelfUpdateCheck,
  fetchLatestCliVersion,
  resolveRegistryBaseUrl,
  parsePackageId,
  registryRepoUrl,
  downloadUrl,
  pickRegistryVersion,
  materializeRegistryArchive,
  fetchAndMaterializeRegistry,
  rewriteDownloadBase,
  modulesRegistryDest,
} from "@/modules/Registry";

export type { FindPathOptions, FindPathResult, ReverseIndex } from "@/modules/Find";
export {
  WORKSPACE_OWNER_KEY,
  buildReverseIndex,
  build_reverse_index,
  buildFindReverseIndex,
  packageOwnerKey,
  lookupInIndex,
  lookup,
  lookupFindPath,
  lookupReverseIndex,
  normalizeFindPath,
  formatFindOwnerLabel,
  ownerLabel,
  formatOwnerLabel,
  findOwnerLabel,
  formatFindOrigin,
  formatOrigin,
  formatSourceOrigin,
  _formatOrigin,
  findPath,
  runFind,
  findDeployedPath,
  runFindPath,
} from "@/modules/Find";

export type {
  ViewError,
  ViewIdentity,
  ViewPackageOptions,
  ViewPackageResult,
} from "@/modules/View";
export { viewPackage, runView, viewLocalPackage, localView } from "@/modules/View";

export type {
  MarketplaceConfigOptions,
  MarketplaceFetchOptions,
  MarketplaceSourceInit,
  MarketplaceSourceKind,
  ValidationResult,
  MarketplacePlugin,
  MarketplaceManifest,
  MarketplaceHostClass,
  ResolvedMarketplaceToken,
  ParsedMarketplaceRef,
  MarketplaceProvenance,
  MarketplaceConcreteDep,
  MarketplacePluginResolution,
  ResolveMarketplacePluginOptions,
  PackageEntry,
  MarketplaceAuthoringConfig,
  LoadMarketplaceResult,
  DetectAuthoringConfigSourceResult,
  CheckMarketplaceAuthoringResult,
  MigrateMarketplaceYmlResult,
  EditorResult,
  SourceValidationResult,
  MarketplaceOutputFormat,
  ResolvedPackage,
  LsRemoteResult,
  LsRemoteFn,
  BuildMarketplaceOutputsOptions,
  MarketplaceOutputWritten,
  BuildMarketplaceOutputsResult,
  ResolveMarketplacePackagesOptions,
  ResolveMarketplacePackagesResult,
  ResolveEffectiveOutputPathOptions,
  ParseMarketplaceFilterResult,
} from "@/modules/Marketplace";

export {
  MarketplaceError,
  MarketplaceNotFoundError,
  MarketplaceFetchError,
  MarketplacePluginNotFoundError,
  MarketplaceUnsupportedSourceError,
  MarketplaceAuthoringError,
  MarketplacePackOutputsError,
  MarketplaceSource,
  createMarketplaceSource,
  createMarketplacePlugin,
  createMarketplaceManifest,
  urlNamesRemoteManifest,
  resolveLocalFilesystemPath,
  classifyMarketplaceHost,
  classifyMarketplaceHostKind,
  marketplaceKindFromHostClass,
  githubApiBaseForHost,
  isUnlockedMarketplaceHost,
  resolveTokenForHost,
  resolveMarketplaceTokenForHost,
  resolveAuthTokenForHost,
  authHeadersForHost,
  parseMarketplaceJson,
  parseMarketplaceRef,
  resolveMarketplacePlugin,
  getBapmConfigDir,
  marketplacesJsonPath,
  marketplaceCacheDir,
  ensureBapmConfigDir,
  listMarketplaces,
  getMarketplace,
  addMarketplace,
  removeMarketplace,
  CACHE_TTL_SECONDS,
  sanitizeCacheName,
  cacheKeyForSource,
  readMarketplaceCache,
  writeMarketplaceCache,
  MAX_MARKETPLACE_JSON_BYTES,
  MARKETPLACE_PATHS,
  fetchMarketplace,
  clearMarketplaceCache,
  autoDetectMarketplacePath,
  validateMarketplace,
  validateMarketplaceAuthoringSource,
  isValidMarketplaceAuthoringSource,
  loadMarketplaceFromBapmYml,
  loadMarketplaceFromLegacyYml,
  detectAuthoringConfigSource,
  loadMarketplaceAuthoringConfig,
  renderMarketplaceBlock,
  renderInitMarketplaceBlock,
  createMarketplaceAuthoringTemplate,
  initMarketplaceAuthoring,
  addMarketplacePackage,
  setMarketplacePackage,
  removeMarketplacePackage,
  checkMarketplaceAuthoring,
  checkAuthoringMarketplace,
  runMarketplaceAuthoringCheck,
  migrateMarketplaceYml,
  migrateLegacyMarketplaceYml,
  runMarketplaceMigrate,
  ensureMarketplacePathWithin,
  resolveEffectiveOutputPath,
  resolveMarketplaceOutputPath,
  formatsEnabledInConfig,
  parseMarketplaceFilter,
  selectOutputFormats,
  normalizeMarketplacePathOverrides,
  resolveMarketplacePackages,
  resolveAuthoringPackages,
  resolveMarketplacePackPackages,
  serializeMarketplaceJson,
  atomicWriteMarketplaceJson,
  buildMarketplaceOutputs,
  emitMarketplacePackOutputs,
  runMarketplaceBuilder,
  writeMarketplacePackOutputs,
  tryLoadMarketplaceAuthoring,
} from "@/modules/Marketplace";

export const BAPM_NAME = "bapm";

export function getVersion(): string {
  return "0.0.0";
}
